# a=(input("My Name is:"))
# b=int(input("My Age is:"))
# print(a)
# print(b)
# name=input()
# age=input()
# print("my name is:",name)
# print("my age is:",age)
# name=input()
# age=input()
# address=input()
# print("my name is:",name)
# print("my age is:",age)
# print("my address",address)
# a=int(input())
# b=int(input())
# c=int(input())
# d=a*b*c
# e=a+b+c
# f=d/e
# print(f)
name=input()
score=int(input())
dep=input()
print("my name",name)
print("my score",score/10,"/10")
print("my dep ",dep)